version: '3.7'

services:
  consumer:
    container_name: pact-consumer
    build:
      context: ./pact-consumer
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - pact

  provider:
    container_name: pact-provider
    build:
      context: ./pact-provider
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - pact

networks:
  pact: